import React from 'react';
import {ReactNode} from 'react';
import Head from "next/head";
import Footer from './footer';
import Header from './header';

interface Props {
  children: ReactNode;
}

const Layout = ({children}: Props) => {
  return (
    <>
      <Head>
        <title>404 motivation not found</title>
        <meta
          name="description"
          content="Generated by create next app"
        />
        <link
          rel="icon"
          href="/favicon.ico"
        />
      </Head>
      <div
        className="
          bg-gray-200
        "
      >
        <header>
          <Header />
        </header>
        <div
          className="
            w-full
          "
        >
          {children}
        </div>
        <footer>
          <Footer />
        </footer>
      </div>
    </>
  );
};

export default Layout;
