import type { InferGetStaticPropsType, NextPage } from "next";
import Head from "next/head";
import { getAllPosts } from "../lib/api";

type Props = InferGetStaticPropsType<typeof getStaticProps>;

export const getStaticProps = async () => {
  const allPosts = getAllPosts(["slug", "title", "date", "tags"]);
  return {
    props: { allPosts },
  };
};

const Home: NextPage<Props> = ({ allPosts }) => {
  return (
    // <div className={styles.container}>
    <div>
      <Head>
        <title>Hello world!</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* <main className={styles.main}> */}
      <main className="w-full bg-red-200">
        {/* <h1 className={styles.title}>記事一覧</h1> */}
        <h1>記事一覧</h1>

        {/* <div className={styles.grid}> */}
        <div className="grid grid-cols-3 gap-4 text-black font-bold">
          {allPosts.map((post) => (
            // <a href={post.slug} className={styles.card} key={post.slug}>
            <a href={post.slug} className="
              block max-w-sm p-6 bg-white border
              border-gray-200 rounded-lg shadow
              hover:bg-gray-100 dark:bg-gray-800
              dark:border-gray-700 dark:hover:bg-gray-700"
              key={post.slug}
            >
              <h2>{post.title}</h2>
              <p>{post.date}</p>
            </a>
          ))}
        </div>
      </main>
      {/* <footer className={styles.footer}> */}
      <footer>
        <p>Powered by Next.js.</p>
      </footer>
    </div>
  );
};

export default Home;
